import {z} from 'genkit';

export const GenerateAppBlueprintInputSchema = z.object({
  appIdea: z.string().describe('The user inputted idea for an app.'),
});
export type GenerateAppBlueprintInput = z.infer<typeof GenerateAppBlueprintInputSchema>;

export const GenerateAppBlueprintOutputSchema = z.object({
  coreProblem: z.string().describe('The core problem that the app solves.'),
  keyFeatures: z.string().describe('The key features of the app.'),
  targetUser: z.string().describe('The target user for the app.'),
});
export type GenerateAppBlueprintOutput = z.infer<typeof GenerateAppBlueprintOutputSchema>;


export const ReviseAppBlueprintInputSchema = z.object({
    initialAppIdea: z
      .string()
      .describe('The user’s initial idea for the app.'),
    currentBlueprint: z
      .string()
      .describe('The current app blueprint generated by the AI, as a JSON string.'),
    userFeedback: z
      .string()
      .describe('The user’s feedback on the current blueprint.'),
  });
export type ReviseAppBlueprintInput = z.infer<typeof ReviseAppBlueprintInputSchema>;

export const ReviseAppBlueprintOutputSchema = GenerateAppBlueprintOutputSchema;
export type ReviseAppBlueprintOutput = z.infer<typeof ReviseAppBlueprintOutputSchema>;
